name: exercise-workflow
on: workflow_dispatch
jobs:
  exercise-test-job1:
    runs-on: ubuntu-latest
    steps:
      - name: Download code
        uses: actions/checkout@v3
      - name: Install dependencies
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Run Lint, build and test
        run: |
          npm ci
          npm run lint
          npm run build
          npm run test
      - name: Output Message
        run: echo "Deployed the workflow successfully"         
            